version: '3'

vars:
    GO_FLAGS: "-s -w"
    TARGETS: [filehash, seeip, uuid, ips2subnets]
    TEST_TARGETS: [ips2subnets]
    TEST_OS: "windows"

tasks:
    show-dir:
        cmds:
            - pwd

    clear:
        cmds:
            - go mod tidy
            - go clean
            - rm -rf ./build
            - mkdir ./build

    test-build:
        cmds:
            - rm -rf ./build/test
            - mkdir ./build/test
            - for: {var: TEST_TARGETS}
              cmd: |
                GOOS={{.TEST_OS}}
                go build -o "./build/test/{{.ITEM}}{{if eq .TEST_OS "windows"}}.exe{{end}}" -v "./cmd/{{.ITEM}}/main.go"
                echo "Test Build - finish building: {{.ITEM}}"

    build-windows:
        shell: bash
        cmds:
            - rm -rf ./build/windows
            - mkdir ./build/windows
            - for: {var: TARGETS}
              cmd: |
                GOOS=windows 
                go build -ldflags="{{.GO_FLAGS}}" -o "./build/windows/{{.ITEM}}.exe" -v "./cmd/{{.ITEM}}/main.go"
                echo "Windows - finish  building: {{.ITEM}}"

    build-linux:
        shell: bash
        cmds:
            - rm -rf ./build/linux
            - mkdir ./build/linux
            - for: {var: TARGETS}
              cmd: |
                GOOS=linux 
                go build -ldflags="{{.GO_FLAGS}}" -o "./build/linux/{{.ITEM}}" -v "./cmd/{{.ITEM}}/main.go"
                echo "Linux - finish building: {{.ITEM}}"

    build:
        deps: [clear]
        cmds:
            - task: build-linux
            - task: build-windows